version: '3.8'

services:
  django-container:
    build: .
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - db_data:/app/db
    ports:
      - 8000:8000
volumes:
  db_data: