# Generated by Django 4.2.3 on 2024-01-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_order_user_order_product_delete_ordereditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(default=''),
        ),
    ]
