# Generated by Django 4.2.3 on 2024-01-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_order_items_product_status_ordereditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
