# Generated by Django 4.2.3 on 2024-01-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
