# Generated by Django 4.2.3 on 2024-01-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_ordereditems_order_order_ordered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Ordered',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.TextField(default=''),
        ),
    ]
