# Generated by Django 4.2.3 on 2024-01-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_user_order_users_remove_order_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditems',
            name='product',
        ),
    ]
