# Generated by Django 4.2.3 on 2024-01-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_ordereditems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='products.order'),
        ),
    ]
