# Generated by Django 4.2.3 on 2024-01-05 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_ordereditems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_product_items', to='products.product'),
        ),
        migrations.DeleteModel(
            name='OrderedItems',
        ),
    ]
